name: Run create_file.bat on Windows VM (Foreground)

on:
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: windows-latest
    env:
      VM_HOST: ${{ secrets.VM_HOST }}
      VM_USERNAME: ${{ secrets.VM_USERNAME }}
      # Add a step to set the private key as a variable (avoid hardcoding)
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload SSH private key (avoid pushing to logs)
        uses: shivamathew/ssh-key-action@v1
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USERNAME }}
          key: ${{ env.PRIVATE_KEY }}
          # Optional: configure passphrase if needed
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}  # Uncomment if applicable

      - name: Connect to Windows VM using WinRM
        uses: microsoft/windows-update@v1.1.1
        with:
          login: ${{ env.VM_USERNAME }}
          # Use a personal access token with WinRM permissions instead of hardcoding password
          password: ${{ secrets.WINRM_ACCESS_TOKEN }}
          # Optional: configure WinRM port if non-standard
          # port: 5985  # Uncomment if needed

      - name: Run create_file.bat in foreground
        run: |
          # Establish WinRM session with persistence (optional for longer tasks)
          Enter-PSSession -ComputerName ${{ env.VM_HOST }} -UseSSL -Authentication Credssp -Credential (New-Object System.Management.Automation.PSCredential (${env:VM_USERNAME}, (ConvertTo-SecureString -AsPlainText -Force -String $env:WINRM_ACCESS_TOKEN).ConvertTo-UnsecureString())))

          # Execute create_file.bat and wait for completion
          Start-Process "C:\Users\vboxuser\create_file.bat" -Wait -NoNewWindow  # Adjust path if needed
