name: Create File on Windows Desktop

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy script to VM
      run: scp -i ${{ secrets.SSH_PRIVATE_KEY }} script.bat ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:C:\script.bat

    - name: Run script on VM
      run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} 'powershell -Command "Start-Process -FilePath C:\script.bat -Wait"'
