name: Create File on Windows Desktop

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy script to VM
      run: |
        scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} create_file.bat ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:C:\create_file.bat

    - name: Run script on VM
      run: |
        $script = @"
        Invoke-Command -ComputerName ${secrets.VM_HOST} -ScriptBlock {
          C:\create_file.bat
        } -Credential (New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "${secrets.VM_USERNAME}", (ConvertTo-SecureString -String "${secrets.VM_PASSWORD}" -AsPlainText -Force))
"@
        Invoke-Expression -Command $script
