name: Create File on Windows Desktop

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy script to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: create_file.bat  # Assuming the script is named create_file.bat in your repository
        target: C:\create_file.bat  # Copy the script to the C:\ drive of the VM

    - name: Run script on VM
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          powershell.exe -Command "Start-Process -FilePath C:\create_file.bat -Wait"
