name: Create File on Windows Desktop

on:
  push:
    branches:
      - main

jobs:
  create-file:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy script to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: script.bat  # Assuming the script is named script.bat in your repository
        target: C:\script.bat  # Copy the script to the C:\ drive of the VM

    - name: Run script on VM
      shell: powershell
      env:
        USERNAME: ${{ secrets.VM_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.VM_HOST }}
      run: |
        $Username = $env:USERNAME
        $SSHPrivateKey = $env:SSH_PRIVATE_KEY
        $Host = $env:HOST

        # Establish SSH connection and execute script on remote Windows machine
        $Command = "powershell -Command `"Start-Process -FilePath 'C:\script.bat' -Wait`""
        $SshCommand = "ssh -i $($SSHKeyFile.FullName) $Username@$Host $Command"
        Invoke-Expression -Command $SshCommand
