name: Build Module

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script on VM
      run: |
        $Username = "${{ secrets.VM_USERNAME }}"
        $RemoteHost = "${{ secrets.VM_HOST }}"

        # Copy the build script to the remote Windows machine using PowerShell Remoting
        Copy-Item -Path "build.ps1" -Destination "\\$RemoteHost\C$\build.ps1" -ToSession (New-PSSession -ComputerName $RemoteHost -Credential (Get-Credential -UserName $Username -Message "Enter password for $Username"))

        # Run the build script on the remote Windows machine using PowerShell Remoting
        Invoke-Command -ComputerName $RemoteHost -Credential (Get-Credential -UserName $Username -Message "Enter password for $Username") -ScriptBlock { & "C:\build.ps1" -Task ModuleBuild }
